/**
 * Asset-free runtime observation records for the licensed SS2 build.
 *
 * An observation is one instrumented, controlled 1v1 action captured from the
 * fingerprinted licensed installation. It stores only independently authored
 * numeric state, ordered RNG samples with call-site metadata, ordered
 * mutations, semantic events, and integrity digests. It never stores game
 * code, assets, screenshots, or install paths.
 *
 * Observations are the runtime half of the golden pipeline: static candidate
 * fixtures stay hypotheses until at least two matching independent
 * observations exist (see promote-1v1-golden.js).
 */

import { createHash } from "node:crypto";

import { RollSource, createOrderedRollTape } from "./ordered-rolls.js";
import { SS2_STAGED_MAX_LENGTH, parseStagedDeclaration } from "./staged-declaration.js";
import {
  SS2_BUILD_SHA256,
  SS2_PROJECTED_COMBATANT_KEYS,
  SS2_STEAM_BUILD_ID,
  assertJsonSafe,
  assertNoAssetPayload,
  assertSs2MutationTraceShape,
  assertSs2ResultEventShape,
  assertSs2ScenarioShape,
  validateSs2OneVsOneFixture
} from "./run-1v1-fixture.js";

export { SS2_PROJECTED_COMBATANT_KEYS };

export const SS2_OBSERVATION_SCHEMA_VERSION = 1;
export const SS2_OBSERVATION_KIND = "ss2-1v1-observation";

/** Documented capture methods; all of them keep the installed files read-only. */
export const ObservationCaptureMethod = Object.freeze({
  /** randomBetween wrapped with an injected deterministic tape. */
  INJECTED_TAPE: "injected-tape-runtime",
  /** rolls recorded without forcing them; only exact roll matches count. */
  PASSIVE: "passive-runtime",
  /**
   * Reference trace generated by src/golden/simulate-capture-trace.js to
   * exercise the pipeline and specify wrapper behavior. Never promotable.
   */
  SIMULATED: "synthetic-simulator"
});

export const SS2_SIMULATED_CAPTURE_METHOD = ObservationCaptureMethod.SIMULATED;

const OBSERVATION_KEYS = Object.freeze([
  "build",
  "capture",
  "digest",
  "events",
  "finalState",
  "kind",
  "mutationTrace",
  "observationId",
  "resultEvent",
  "samples",
  "scenario",
  "schemaVersion",
  "target"
]);
const CAPTURE_KEYS = Object.freeze([
  "captureToolVersion",
  "installHashVerifiedAfter",
  "installHashVerifiedBefore",
  "method",
  "mutationGranularity",
  "observedAt",
  "sessionId"
]);
/**
 * The three capture attestations the wrapper mints on the trace's `end` line
 * and `capture-ingest.js` carries into the record.
 *
 * They are OPTIONAL, and deliberately so. Every observation committed before
 * the fields existed was ingested by a version that validated and then
 * discarded them, and an observation's digest covers its own record — adding a
 * required field would invalidate the digest of every one of those records and
 * with it the provenance of every golden that cites them. So a legacy record
 * that carries none of them still validates, still matches, and still promotes;
 * it simply carries no assurance on those points. What forces new evidence to
 * carry them is the mandatory check at ingest (see capture-ingest.js), not this
 * schema.
 *
 * - `overdraw`: draws the armed recording window made AFTER the injected tape
 *   ran out. Those draws are invisible in the trace itself, so without this
 *   count a run that drew more randomness than the candidate models is
 *   indistinguishable from one that matched it. Ingest refuses any trace
 *   reporting a non-zero count, so the only value a valid record can carry is
 *   0 — the field is an attestation that the guard ran, not a measurement.
 * - `launchNonce`: minted inside the player from values the launcher does not
 *   supply. `sessionId` and `observationId` are both operator strings; the
 *   nonce is the one identity field on a record that the operator did not
 *   choose, which is why the promotion gate refuses two observations that
 *   share one.
 * - `staged`: every combatant field the WRAPPER wrote before the observed
 *   action, and the value that stuck once the game's own construction had
 *   finished. Its absence means the scenario is one the game produced unaided,
 *   which is what 22 of the 23 promoted goldens rest on — the exception is
 *   `golden-armoured-deflection-threshold-cleared`, whose scenario the wrapper
 *   staged and which therefore carries this key. Its presence does not make
 *   an observation weaker evidence — the game still resolved the action, and
 *   the formulas under measurement operate on whatever inputs they are given —
 *   but it does mean nobody has shown the game's own progression can *reach*
 *   this scenario. A reviewer has to be able to tell the two apart, so the
 *   field is carried into the record and surfaced by the promotion gate.
 */
const CAPTURE_OPTIONAL_KEYS = Object.freeze(["launchNonce", "overdraw", "staged"]);

export const SS2_CAPTURE_ATTESTATION_KEYS = CAPTURE_OPTIONAL_KEYS;
const SAMPLE_KEYS = Object.freeze(["callSite", "injected", "label", "max", "min", "source", "value"]);
const PROJECTED_BOOLEAN_KEYS = new Set([
  "burning",
  "frozen",
  "life_stolen",
  "poison",
  "taunted1",
  "taunted2"
]);

const TOKEN_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const CALL_SITE_PATTERN = /^(?:overlay|root|sprite):/;
const DIGEST_PATTERN = /^[a-f0-9]{64}$/;
const COSMETIC_DEBRIS_PATTERN = /^armour-debris-\d+-(?:x|y|rotation)$/;
/**
 * The spell ingress's `damage_method` argument. Byte-verified (battle map lines
 * 338-350) as register r5, passed straight to
 * `defenderClip.gotoAndPlay(damage_method)` — "for this ingress the
 * `damage_method` argument is the defender's animation label". Unlike
 * `defender_hurt`, whose four methods are a closed byte-verified dispatch
 * (map lines 242-244), the animation labels of export 1241 are only partially
 * enumerated by the map (line 514 summarises "condition effects (1911-2004)"
 * without naming them), and the direct-damage spell table records a label for
 * fireball ("burning", map line 388) and lightning bolt ("lightning", map line
 * 391) only. Closing the set here would be a guess, so the shape is checked and
 * the value is not: a spell whose label the map does not record carries `null`
 * in its candidate and diverges loudly against a live capture.
 */
const SPELL_ANIMATION_LABEL_PATTERN = /^[A-Za-z][A-Za-z0-9_]{0,31}$/;

/**
 * One entry of the staging declaration: `side.field=value`.
 *
 * `field` is deliberately the same token shape the trace's `set` paths use
 * (`SET_PATH_PATTERN` in capture-ingest.js), not the closed
 * `SS2_PROJECTED_COMBATANT_KEYS` set: the armoured captures stage per-piece
 * `*_defence` ratings that the wrapper's default watch list omits, and a
 * declaration that could not name them would be a declaration that lies by
 * omission.
 *
 * `value` admits a decimal number or a boolean and nothing else. Every watched
 * combatant field is numeric or boolean (see PROJECTED_BOOLEAN_KEYS and the
 * `Number.isFinite` arm of assertFinalStateShape), and admitting free strings
 * would let a comma or an `=` into a value and make the list ambiguous to
 * split.
 */
/** The staging grammar now lives in `staged-declaration.js`; see that file for why. */
export { SS2_STAGED_MAX_LENGTH };

export class ObservationError extends Error {
  constructor(message, options = {}) {
    super(message, options);
    this.name = new.target.name;
  }
}

export class ObservationValidationError extends ObservationError {}

/** A fixture mutation reason that no wrapper hook is mapped to. */
export class HookAttributionError extends ObservationError {}

/**
 * The hook `capture-ingest.js` stamps on the `/result` entry it synthesizes.
 *
 * `/result` is a pipeline convention rather than a watched game field, so no
 * `set` line ever carries it; ingest mints the entry from the observed `death`
 * and `overlay-label` events and labels it with this constant. The literal
 * lives in `capture-ingest.js` (another track's file, and importing it here
 * would be a cycle), so the two are pinned by checking this value against the
 * `/result` rows of the committed observation records — output ingest really
 * produced — rather than against a second copy of the same literal, which
 * would move with it and assert nothing.
 */
export const SS2_RESULT_BRIDGE_HOOK = "result-bridge";

/**
 * Wrapper hook attribution per static mutation reason — the physical
 * (`damagecharacter`) ingress.
 *
 * A fixture names each mutation by the STATIC REASON the candidate model
 * assigns it; a wrapper reports the INGRESS FUNCTION the write happened
 * inside. This table is the translation between them, and it is what makes
 * `matchSs2ObservationToFixture` able to compare an attribution instead of
 * discarding it. The convention is the ingress that owns the assignment, not
 * the innermost helper: `stat-clamp` is `check_stats`' arithmetic but is
 * attributed to whichever ingress called it.
 *
 * `src/golden/simulate-capture-trace.js` holds a second copy under the names
 * `HOOK_FOR_STATIC_REASON`/`SPELL_HOOK_FOR_STATIC_REASON`, because that module
 * imports this one and the reverse import would be a cycle. The copies are
 * pinned equal by a test, and the reference simulator's own end-to-end
 * self-check would fail on every fixture if they ever drifted. The canonical
 * home is here, with the matcher that consumes it.
 */
export const SS2_HOOK_FOR_STATIC_REASON = Object.freeze({
  "physical-damage": "damagecharacter",
  "magic-damage": "magic-damage-character",
  "psyche-up": "magic-damage-character",
  "breastplate-stamina": "damagecharacter",
  "stat-clamp": "damagecharacter",
  "weapon-enchantment": "damagecharacter",
  "remove-armour-piece": "remove-armour",
  "remove-armour-clamp": "remove-armour",
  "death-status-clear": "death",
  "death-taunt-clear": "death"
});

/**
 * The same table as seen from the spell ingress.
 *
 * Two reasons are shared with the physical path but belong to a different
 * function there: the breastplate stamina join and `check_stats` are steps 5
 * and 6 of `magic_damage_character` itself, so a wrapper attributing by call
 * frame reports `magic-damage-character` for both during a spell action.
 * `death-*` stays `death`, which really is the shared function.
 */
export const SS2_SPELL_HOOK_FOR_STATIC_REASON = Object.freeze({
  ...SS2_HOOK_FOR_STATIC_REASON,
  "breastplate-stamina": "magic-damage-character",
  "stat-clamp": "magic-damage-character"
});

/**
 * Parse a staging declaration into its ordered entries, or throw naming the
 * exact reason.
 *
 * This is the single definition of the grammar. `capture-ingest.js` calls it to
 * validate the trace's `end.staged` (re-reporting any failure against the line
 * that carried it) and `assertCaptureBlock` calls it to validate the record's
 * `capture.staged`, so a record can never carry a shape the trace could not.
 *
 * Absence is the encoding for "the wrapper staged nothing". The empty string is
 * therefore rejected rather than accepted as a synonym: two spellings of one
 * fact would mean two records that claim the same thing digest differently, and
 * a reader could not tell "staged nothing" from "forgot to say".
 */
/**
 * The observation-side spelling of the staging grammar.
 *
 * Kept as a named export because `capture-ingest.js` and this module's own
 * `assertObservation` both call it, and because the promotion gate's refusal
 * message names it. The grammar itself moved to `staged-declaration.js` so that
 * `run-1v1-fixture.js` can validate `provenance.staged` with the SAME parser
 * without importing this module, which would be a cycle.
 */
export function parseSs2StagedDeclaration(text, path = "capture.staged") {
  return parseStagedDeclaration(text, path, ObservationValidationError);
}

function isPlainObject(value) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function assertExactKeys(value, expectedKeys, path) {
  const actual = Object.keys(value).sort();
  const expected = [...expectedKeys].sort();
  if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) {
    throw new ObservationValidationError(`${path} has unexpected or missing fields.`);
  }
}

/**
 * Every required key present, and no key outside required ∪ optional. Used
 * only where a block has genuinely optional members; everywhere else the
 * exact-keys check stays, because an unexpected field is a defect.
 */
function assertKeysWithOptional(value, requiredKeys, optionalKeys, path) {
  const allowed = new Set([...requiredKeys, ...optionalKeys]);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) throw new ObservationValidationError(`${path} has an unexpected field ${key}.`);
  }
  for (const key of requiredKeys) {
    if (!Object.hasOwn(value, key)) throw new ObservationValidationError(`${path} is missing the field ${key}.`);
  }
}

function cloneJson(value) {
  return JSON.parse(JSON.stringify(value));
}

function canonicalize(value) {
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalize(item)).join(",")}]`;
  }
  if (value !== null && typeof value === "object") {
    const keys = Object.keys(value).sort();
    return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalize(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

/** Deterministic JSON text: sorted object keys, arrays kept in order. */
export function canonicalJsonStringify(value, path = "value") {
  assertJsonSafe(value, path);
  return canonicalize(value);
}

export function sha256OfCanonicalJson(value, path = "value") {
  return createHash("sha256").update(canonicalJsonStringify(value, path), "utf8").digest("hex");
}

/**
 * The digest covers the full record except the digest field itself, so every
 * observation (with its unique id and capture metadata) digests uniquely.
 */
export function computeSs2ObservationDigest(record) {
  if (!isPlainObject(record)) throw new ObservationValidationError("The observation must be an object.");
  const undigested = { ...record };
  delete undigested.digest;
  return sha256OfCanonicalJson(undigested, "observation");
}

function assertBuildBlock(build, path) {
  if (
    !isPlainObject(build) ||
    build.fingerprintSchemaVersion !== 1 ||
    build.steamBuildId !== SS2_STEAM_BUILD_ID ||
    build.ss2Sha256 !== SS2_BUILD_SHA256
  ) {
    throw new ObservationValidationError(
      `${path} must match fingerprint schema 1, Steam build ${SS2_STEAM_BUILD_ID}, and the pinned SS2 SHA-256.`
    );
  }
  assertExactKeys(build, ["fingerprintSchemaVersion", "ss2Sha256", "steamBuildId"], path);
}

function assertCaptureBlock(capture) {
  if (!isPlainObject(capture)) throw new ObservationValidationError("capture must be an object.");
  assertKeysWithOptional(capture, CAPTURE_KEYS, CAPTURE_OPTIONAL_KEYS, "capture");
  if (typeof capture.sessionId !== "string" || !TOKEN_PATTERN.test(capture.sessionId)) {
    throw new ObservationValidationError("capture.sessionId must be a valid token.");
  }
  if (
    typeof capture.captureToolVersion !== "string" ||
    capture.captureToolVersion.trim().length === 0 ||
    capture.captureToolVersion.length > 128
  ) {
    throw new ObservationValidationError("capture.captureToolVersion must be a non-empty string.");
  }
  if (!Object.values(ObservationCaptureMethod).includes(capture.method)) {
    throw new ObservationValidationError(
      `capture.method must be one of: ${Object.values(ObservationCaptureMethod).join(", ")}.`
    );
  }
  if (typeof capture.observedAt !== "string" || Number.isNaN(Date.parse(capture.observedAt))) {
    throw new ObservationValidationError("capture.observedAt must be a parseable timestamp.");
  }
  if (capture.installHashVerifiedBefore !== true || capture.installHashVerifiedAfter !== true) {
    throw new ObservationValidationError(
      "The installed SS2 hash must be verified before and after every capture session."
    );
  }
  if (capture.mutationGranularity !== "property-watch") {
    throw new ObservationValidationError(
      "capture.mutationGranularity must be property-watch; coarser capture cannot match ordered mutation traces."
    );
  }
  // Zero is the only value a valid record can carry: ingest refuses any trace
  // whose armed window drew past the injected tape, so a record claiming a
  // non-zero count is a record of a divergence that should never have become
  // one. Checked as `!== 0` rather than as a range so a string "0", a null, or
  // a float are all refused with the same message.
  if (Object.hasOwn(capture, "overdraw") && capture.overdraw !== 0) {
    throw new ObservationValidationError(
      "capture.overdraw must be 0 when present: it attests that the armed recording window made no " +
      "draw after the injected tape ran out, and ingest refuses every trace that reports otherwise."
    );
  }
  if (
    Object.hasOwn(capture, "launchNonce") &&
    (typeof capture.launchNonce !== "string" || !TOKEN_PATTERN.test(capture.launchNonce))
  ) {
    throw new ObservationValidationError("capture.launchNonce must be a valid token when present.");
  }
  // Shape only. Whether the declared values actually stuck is checked at ingest
  // against the staged state dump, which a record no longer carries.
  if (Object.hasOwn(capture, "staged")) parseSs2StagedDeclaration(capture.staged, "capture.staged");
}

function assertSampleShape(sample, index) {
  if (!isPlainObject(sample)) {
    throw new ObservationValidationError(`samples[${index}] must be an object.`);
  }
  assertExactKeys(sample, SAMPLE_KEYS, `samples[${index}]`);
  if (typeof sample.callSite !== "string" || sample.callSite.length > 256 || !CALL_SITE_PATTERN.test(sample.callSite)) {
    throw new ObservationValidationError(
      `samples[${index}].callSite must be an overlay:, root:, or sprite: identifier.`
    );
  }
  if (typeof sample.injected !== "boolean") {
    throw new ObservationValidationError(`samples[${index}].injected must be boolean.`);
  }
  if (sample.injected && sample.source !== RollSource.RANDOM_BETWEEN) {
    throw new ObservationValidationError(
      `samples[${index}] cannot be injected: only randomBetween rolls are injectable; ` +
      "AVM1 RandomNumber opcode rolls can only be recorded."
    );
  }
}

/**
 * A live capture cannot carry an opcode sample at all, so a record claiming one
 * is refused rather than quietly excluded.
 *
 * The exclusion this closes was a real hole, demonstrated. `armour-debris-*`
 * opcode rolls are dropped from BOTH sides before comparison, by label regex —
 * so an observation carrying the fixture's 7 samples plus 120 extra rolls
 * labelled `armour-debris-N-x` validated, matched a 7-sample fixture, and
 * promoted. Two observations differing by 120 draws matched each other. That
 * directly contradicts the runtime-capture doc's own list, which puts "the
 * NUMBER of draws in the armed window" under *genuinely observed*: an arbitrary
 * number was invisible, and `overdraw` does not cover them because they are
 * recorded rather than past-the-tape.
 *
 * Closing the channel rather than widening the comparison is the right shape,
 * because nothing real produces one: the opcode stream cannot be observed by
 * any instrumentation the wrapper has (that is why the exclusion exists), 0 of
 * the 67 committed records carry such a sample, the reference simulator emits
 * none, and the wrapper's tape excludes them. The simulator is exempt because
 * its traces are a specification of shapes, not a capture.
 */
function assertNoUncapturableSamples(samples, method) {
  if (method === ObservationCaptureMethod.SIMULATED) return;
  for (let index = 0; index < samples.length; index += 1) {
    if (samples[index].source === RollSource.RANDOM_NUMBER) {
      throw new ObservationValidationError(
        `samples[${index}] is a ${RollSource.RANDOM_NUMBER} sample, which no live capture can ` +
        "record: the AVM1 opcode stream is not observable by the wrapper, which is precisely why " +
        "cosmetic opcode rolls are excluded from matching. Admitting one would open an unbounded " +
        "channel of draws that comparison cannot see."
      );
    }
  }
}

function tapeProjection(samples) {
  return samples.map((sample) => ({
    label: sample.label,
    source: sample.source,
    min: sample.min,
    max: sample.max,
    value: sample.value
  }));
}

/**
 * Cosmetic debris rolls come from the AVM1 RandomNumber opcode after a piece
 * is already removed. The opcode can be neither injected nor recorded by the
 * function-wrap instrumentation, and the rolls never change combat state, so
 * they are excluded from observation comparisons entirely. Fixtures still
 * document them (and the static harness replays them) as part of the native
 * roll stream.
 */
export function isCosmeticDebrisSample(sample) {
  return sample.source === RollSource.RANDOM_NUMBER && COSMETIC_DEBRIS_PATTERN.test(sample.label);
}

function assertEventShape(event, index) {
  if (!isPlainObject(event)) throw new ObservationValidationError(`events[${index}] must be an object.`);
  switch (event.type) {
    case "defender-hurt":
      assertExactKeys(event, ["method", "type"], `events[${index}]`);
      if (!["normal", "critical", "taunt", "grievous"].includes(event.method)) {
        throw new ObservationValidationError(`events[${index}].method must be a mapped defender_hurt method.`);
      }
      return;
    case "defender-blocked":
      assertExactKeys(event, ["type"], `events[${index}]`);
      return;
    /**
     * The spell ingress. `magic_damage_character`'s complete byte-verified call
     * inventory (map lines 366-371) contains neither `defender_hurt` nor
     * `defender_blocked` — it is "the parallel spell/effect ingress" (map line
     * 381) that the wrapper must observe in its own right. `method` is its
     * `damage_method` argument, the defender animation label (map lines
     * 346-350), and is `null` when the map records no label for that spell.
     */
    case "magic-damage":
      assertExactKeys(event, ["method", "type"], `events[${index}]`);
      if (
        event.method !== null &&
        (typeof event.method !== "string" || !SPELL_ANIMATION_LABEL_PATTERN.test(event.method))
      ) {
        throw new ObservationValidationError(
          `events[${index}].method must be null or a defender animation label.`
        );
      }
      return;
    case "death":
      assertExactKeys(event, ["side", "type"], `events[${index}]`);
      if (event.side !== "hero" && event.side !== "villain") {
        throw new ObservationValidationError(`events[${index}].side must be hero or villain.`);
      }
      return;
    case "overlay-label":
      assertExactKeys(event, ["label", "type"], `events[${index}]`);
      if (event.label !== "combatwon" && event.label !== "combatlost") {
        throw new ObservationValidationError(`events[${index}].label must be combatwon or combatlost.`);
      }
      return;
    default:
      throw new ObservationValidationError(`events[${index}] has an unsupported type: ${String(event.type)}.`);
  }
}

function assertResultEventShape(resultEvent) {
  assertSs2ResultEventShape(resultEvent, "resultEvent", ObservationValidationError);
}

function assertFinalStateShape(finalState, resultEvent) {
  if (!isPlainObject(finalState)) throw new ObservationValidationError("finalState must be an object.");
  assertExactKeys(finalState, ["hero", "result", "villain"], "finalState");
  for (const side of ["hero", "villain"]) {
    const combatant = finalState[side];
    if (!isPlainObject(combatant)) {
      throw new ObservationValidationError(`finalState.${side} must be an object.`);
    }
    assertExactKeys(combatant, SS2_PROJECTED_COMBATANT_KEYS, `finalState.${side}`);
    for (const [key, value] of Object.entries(combatant)) {
      if (PROJECTED_BOOLEAN_KEYS.has(key)) {
        if (typeof value !== "boolean") {
          throw new ObservationValidationError(`finalState.${side}.${key} must be boolean.`);
        }
      } else if (!Number.isFinite(value)) {
        throw new ObservationValidationError(`finalState.${side}.${key} must be numeric.`);
      }
    }
  }
  if (resultEvent === null) {
    if (finalState.result !== null) {
      throw new ObservationValidationError("finalState.result must be null when no result event was observed.");
    }
    return;
  }
  try {
    assertJsonSafe(finalState.result, "finalState.result");
  } catch (error) {
    throw new ObservationValidationError(error.message, { cause: error });
  }
  const expectedResult = { ...resultEvent };
  delete expectedResult.type;
  if (canonicalize(finalState.result) !== canonicalize(expectedResult)) {
    throw new ObservationValidationError("finalState.result must equal the observed result event payload.");
  }
}

function assertResultConsistency(record) {
  const overlayEvents = record.events.filter((event) => event.type === "overlay-label");
  const deathEvents = record.events.filter((event) => event.type === "death");
  if (record.resultEvent === null) {
    if (overlayEvents.length > 0) {
      throw new ObservationValidationError("An overlay-label event requires a matching resultEvent.");
    }
    return;
  }
  if (overlayEvents.length !== 1 || deathEvents.length !== 1) {
    throw new ObservationValidationError(
      "A result-bearing observation needs exactly one death and one overlay-label event."
    );
  }
  if (deathEvents[0].side !== record.resultEvent.loserSide) {
    throw new ObservationValidationError("The death event side must match resultEvent.loserSide.");
  }
  if (overlayEvents[0].label !== record.resultEvent.overlayLabel) {
    throw new ObservationValidationError("The overlay-label event must match resultEvent.overlayLabel.");
  }
}

/** Validate one runtime observation record, including its digest. */
export function validateSs2Observation(record) {
  if (!isPlainObject(record)) throw new ObservationValidationError("The observation must be an object.");
  assertExactKeys(record, OBSERVATION_KEYS, "observation");
  if (record.schemaVersion !== SS2_OBSERVATION_SCHEMA_VERSION) {
    throw new ObservationValidationError(`schemaVersion must be ${SS2_OBSERVATION_SCHEMA_VERSION}.`);
  }
  if (record.kind !== SS2_OBSERVATION_KIND) {
    throw new ObservationValidationError(`kind must be ${SS2_OBSERVATION_KIND}.`);
  }
  if (typeof record.observationId !== "string" || !TOKEN_PATTERN.test(record.observationId)) {
    throw new ObservationValidationError("observationId must be a valid token.");
  }
  assertBuildBlock(record.build, "build");
  assertCaptureBlock(record.capture);
  if (!isPlainObject(record.target)) throw new ObservationValidationError("target must be an object.");
  assertExactKeys(record.target, ["fixtureId"], "target");
  if (typeof record.target.fixtureId !== "string" || !/^[a-z0-9][a-z0-9-]{0,127}$/.test(record.target.fixtureId)) {
    throw new ObservationValidationError("target.fixtureId must be a lowercase token.");
  }
  assertSs2ScenarioShape(record.scenario, "scenario", ObservationValidationError);
  if (!Array.isArray(record.samples) || record.samples.length === 0 || record.samples.length > 200) {
    throw new ObservationValidationError("samples must be a non-empty array of at most 200 rolls.");
  }
  record.samples.forEach((sample, index) => assertSampleShape(sample, index));
  assertNoUncapturableSamples(record.samples, record.capture.method);
  try {
    createOrderedRollTape(tapeProjection(record.samples));
  } catch (error) {
    throw new ObservationValidationError(`samples: ${error.message}`, { cause: error });
  }
  const injectedCount = record.samples.filter((sample) => sample.injected).length;
  if (record.capture.method === ObservationCaptureMethod.PASSIVE && injectedCount > 0) {
    throw new ObservationValidationError("passive-runtime captures cannot contain injected samples.");
  }
  if (record.capture.method !== ObservationCaptureMethod.PASSIVE && injectedCount === 0) {
    throw new ObservationValidationError(
      `${record.capture.method} captures must contain at least one injected sample.`
    );
  }
  /*
   * `injected-tape-runtime` is the one method that names a tape, and it means
   * EVERY recorded roll came off it — "at least one" was too weak for it.
   *
   * Three facts close the gap with nothing left over. The wrapper's sole roll
   * emitter stamps `injected: true` unconditionally. A draw made after the tape
   * ran out is never emitted at all — it increments `capture.overdraw`, which
   * ingest refuses non-zero. And `assertNoUncapturableSamples` has already
   * refused the only source that could honestly be uninjected here, the
   * RandomNumber opcode. So a sample claiming `injected: false` on this method
   * claims the wrapper WATCHED a roll it did not force, which is a stronger
   * kind of evidence than the method can produce, and the field is not compared
   * anywhere else: `comparableSamples` drops it before matching. All 407
   * samples across the committed records are injected, so requiring it refuses
   * nothing real.
   *
   * Its sibling `callSite` is deliberately NOT pinned. The wrapper has one roll
   * emitter and stamps one compile-time constant, so any check on the value
   * compares a hard-coded constant to a hard-coded constant: it could not fail
   * on a real capture and would attest nothing about where the roll came from.
   * The honest statement is that `callSite` — like `label`, `min`, `max` and
   * `value` on an injected sample — is the pipeline's own input read back, not
   * an observation, and that belongs in the record's documentation rather than
   * in a check that looks like verification.
   */
  if (
    record.capture.method === ObservationCaptureMethod.INJECTED_TAPE &&
    injectedCount !== record.samples.length
  ) {
    throw new ObservationValidationError(
      `${ObservationCaptureMethod.INJECTED_TAPE} captures must have every sample injected; ` +
      `${record.samples.length - injectedCount} of ${record.samples.length} claim to be rolls the ` +
      "wrapper observed rather than served, which its single roll emitter cannot produce."
    );
  }
  assertSs2MutationTraceShape(record.mutationTrace, "mutationTrace", ObservationValidationError);
  if (record.mutationTrace.length > 500) {
    throw new ObservationValidationError("mutationTrace must contain at most 500 entries.");
  }
  if (!Array.isArray(record.events) || record.events.length > 50) {
    throw new ObservationValidationError("events must be an array of at most 50 entries.");
  }
  record.events.forEach((event, index) => assertEventShape(event, index));
  assertResultEventShape(record.resultEvent);
  assertFinalStateShape(record.finalState, record.resultEvent);
  assertResultConsistency(record);
  try {
    assertJsonSafe(record, "observation");
    assertNoAssetPayload(record, "observation");
  } catch (error) {
    throw new ObservationValidationError(error.message, { cause: error });
  }
  if (typeof record.digest !== "string" || !DIGEST_PATTERN.test(record.digest)) {
    throw new ObservationValidationError("digest must be a lowercase SHA-256 hex digest.");
  }
  const expectedDigest = computeSs2ObservationDigest(record);
  if (record.digest !== expectedDigest) {
    throw new ObservationValidationError("digest does not match the record contents.");
  }
  return record;
}

function comparableSamples(samples) {
  return samples
    .filter((sample) => !isCosmeticDebrisSample(sample))
    .map((sample) => ({
      label: sample.label,
      source: sample.source,
      min: sample.min,
      max: sample.max,
      value: sample.value
    }));
}

/**
 * The projection two independent observations must agree on. Identity and
 * capture metadata are excluded (they must differ — `capture.launchNonce`
 * emphatically so: two records that agree on it are the same launch, which is
 * why the promotion gate refuses them); cosmetic debris rolls are
 * excluded (unobservable and combat-irrelevant); mutation reasons are wrapper
 * hook attributions and are kept because independent runs of the same tooling
 * must attribute alike.
 *
 * `capture.staged` is excluded here too, and that exclusion is exactly why the
 * promotion gate has to compare it itself. Two observations can agree on every
 * channel in this projection — same scenario values, same tape, same mutations,
 * same final state — while one of them had those values written in by the
 * wrapper and the other got them from the game. The values are what this
 * projection sees; how they came to be is not a value.
 */
export function projectSs2ObservationForComparison(record) {
  return cloneJson({
    build: record.build,
    target: record.target,
    scenario: record.scenario,
    samples: comparableSamples(record.samples),
    mutationTrace: record.mutationTrace,
    events: record.events,
    resultEvent: record.resultEvent,
    finalState: record.finalState
  });
}

/**
 * Fields two records of the same action MUST be free to differ on: identity and
 * the capture metadata (`launchNonce` emphatically — two records agreeing on it
 * are one launch, which the promotion gate refuses separately), plus the digest,
 * which is a function of everything else.
 */
const SS2_PAIRWISE_EXCLUDED_KEYS = Object.freeze(["capture", "observationId", "digest"]);

/**
 * The surface two observations must agree on when compared TO EACH OTHER.
 *
 * WHY THIS DOES NOT REUSE `projectSs2ObservationForComparison`, which is the
 * whole point of the function existing:
 *
 * That projection is shared with `matchSs2ObservationToFixture` — both route
 * their samples through `comparableSamples`. So an exclusion added there to make
 * the MATCHER tolerant silently makes the PAIRWISE GATE blind to the same field,
 * and the gate whose job is to catch two records disagreeing about a field is
 * switched off by the very edit that stops the field being compared. That is not
 * hypothetical: with the prescribed `staminaleft` exclusion patched in, an
 * auditor promoted a golden from two records disagreeing by 99,992 stamina — one
 * negative, one 10^13 above `staminamax` — with this gate installed and silent.
 *
 * So this projection is built by ENUMERATING the record's own keys and dropping
 * a named few, rather than by listing the channels to keep. It fails closed: a
 * field added to the schema later is compared by default and has to be
 * deliberately exempted here to stop being compared. Nothing the matcher does to
 * its own projection can reach it.
 *
 * It is also strictly wider than the matcher's view, which closes a blind spot
 * the audit named: `callSite` and `injected` survive here, so two records that
 * disagree about where a roll came from no longer corroborate each other.
 *
 * Measured before landing: all 29 cited observation pairs across the 22 promoted
 * goldens agree under this surface, so it refuses no legitimate promotion.
 */
export function projectSs2ObservationForPairwiseComparison(record) {
  const projected = {};
  for (const key of Object.keys(record).sort()) {
    if (SS2_PAIRWISE_EXCLUDED_KEYS.includes(key)) continue;
    projected[key] = record[key];
  }
  return cloneJson(projected);
}

const MAX_DIFFERENCES = 200;

function pushDifference(differences, difference) {
  if (differences.length < MAX_DIFFERENCES) differences.push(difference);
}

function collectDifferences(expected, actual, path, differences) {
  if (differences.length >= MAX_DIFFERENCES) return;
  const bothObjects =
    expected !== null && actual !== null &&
    typeof expected === "object" && typeof actual === "object" &&
    Array.isArray(expected) === Array.isArray(actual);
  if (!bothObjects) {
    if (canonicalize(expected ?? null) !== canonicalize(actual ?? null)) {
      pushDifference(differences, {
        path,
        expected: cloneJson(expected ?? null),
        actual: cloneJson(actual ?? null)
      });
    }
    return;
  }
  if (Array.isArray(expected)) {
    if (expected.length !== actual.length) {
      pushDifference(differences, {
        path: `${path}/length`,
        expected: expected.length,
        actual: actual.length
      });
    }
    const shared = Math.min(expected.length, actual.length);
    for (let index = 0; index < shared; index += 1) {
      if (differences.length >= MAX_DIFFERENCES) return;
      collectDifferences(expected[index], actual[index], `${path}/${index}`, differences);
    }
    return;
  }
  const keys = [...new Set([...Object.keys(expected), ...Object.keys(actual)])].sort();
  for (const key of keys) {
    if (differences.length >= MAX_DIFFERENCES) return;
    if (!Object.hasOwn(expected, key) || !Object.hasOwn(actual, key)) {
      pushDifference(differences, {
        path: `${path}/${key}`,
        expected: Object.hasOwn(expected, key) ? cloneJson(expected[key]) : undefined,
        actual: Object.hasOwn(actual, key) ? cloneJson(actual[key]) : undefined
      });
      continue;
    }
    collectDifferences(expected[key], actual[key], `${path}/${key}`, differences);
  }
}

/**
 * Compare two validated observations to EACH OTHER.
 *
 * Uses `projectSs2ObservationForPairwiseComparison`, deliberately NOT the
 * matcher's projection — see that function for why sharing one would let a
 * matcher-side exclusion switch this gate off.
 */
export function ss2ObservationsMatch(left, right) {
  validateSs2Observation(left);
  validateSs2Observation(right);
  const differences = [];
  collectDifferences(
    projectSs2ObservationForPairwiseComparison(left),
    projectSs2ObservationForPairwiseComparison(right),
    "",
    differences
  );
  return { match: differences.length === 0, differences };
}

/**
 * Semantic events a fixture's expected outcome implies at runtime.
 *
 * Which ingress ran is a property of the staged action, so it is read from the
 * scenario, not from the derived calculation: `scenario.spellId` selects the
 * spell ingress and `scenario.attackDirection` the physical one (the fixture
 * schema requires exactly one of them).
 *
 * The physical branch below is unchanged and is pinned by a regression test:
 * a miss dispatches `defender_blocked()` alone (map line 250), a hit dispatches
 * `defender_hurt(<method>)` (map lines 242-244), and a defeat adds the `death`
 * call and the overlay transition it drives (map lines 457-466).
 */
export function deriveExpectedEventsFromSs2Fixture(fixture) {
  const events = [];
  if (fixture?.scenario?.spellId !== undefined) {
    // `magic_damage_character` calls neither `defender_hurt` nor
    // `defender_blocked` (its complete call inventory is byte-verified at map
    // lines 366-371), and it has no hit roll at all — the caller already rolled
    // the damage. So there is no hit/miss branch here: the ingress running IS
    // the event, and its `damage_method` argument is the animation label it
    // plays on the defender (map lines 346-350).
    events.push({ type: "magic-damage", method: fixture.expected?.calculation?.damageMethod ?? null });
  } else if (fixture?.expected?.calculation?.hit !== true) {
    return [{ type: "defender-blocked" }];
  } else {
    events.push({ type: "defender-hurt", method: fixture.expected.calculation.dispatchedMethod });
  }
  if (fixture.expected.resultEvent) {
    events.push({ type: "death", side: fixture.expected.resultEvent.loserSide });
    events.push({ type: "overlay-label", label: fixture.expected.resultEvent.overlayLabel });
  }
  return events;
}

function candidateIdFor(fixtureId) {
  return fixtureId.startsWith("golden-") ? `candidate-${fixtureId.slice("golden-".length)}` : fixtureId;
}

/**
 * One mutation projected for matching: ordering, the write itself, and the
 * hook the write must be attributed to.
 *
 * The two sides speak different vocabularies and the key is named `hook`
 * rather than `reason` to keep that visible in a divergence path. A fixture
 * entry carries a STATIC reason (`physical-damage`, `stat-clamp`) — the
 * candidate model's name for the assignment. An observation entry carries the
 * WRAPPER's attribution: the ingress function the write happened inside,
 * copied from the raw trace's `set.hook` by `capture-ingest.js`. Translating
 * the first into the second is what makes them comparable; see
 * `hookForFixtureMutation`.
 */
function projectTraceForMatching(trace, hookAt) {
  return trace.map((entry, index) => ({
    sequence: entry.sequence,
    path: entry.path,
    before: entry.before,
    after: entry.after,
    hook: hookAt(entry, index)
  }));
}

/**
 * The hook a wrapper must report for one fixture mutation.
 *
 * Which table applies is a property of the STAGED ACTION, not of the derived
 * calculation, so it is keyed on `scenario.spellId !== undefined` — the same
 * discriminator `deriveExpectedEventsFromSs2Fixture` above and
 * `simulate-capture-trace.js` already use, and the same one the fixture schema
 * enforces by requiring exactly one action identity.
 *
 * An unmapped reason THROWS rather than producing a difference. A difference
 * would report "this observation diverges" when the real fault is a gap in
 * this table, sending the reader to re-capture evidence that was never wrong.
 * Nothing in the repository reaches it today: every static reason in every
 * committed fixture is mapped.
 */
function hookForFixtureMutation(fixture, entry, index) {
  // `/result` is not a game write. It is a pipeline convention that ingest
  // synthesizes from the observed `death` + `overlay-label` pair, stamping its
  // own constant. Comparing it therefore proves nothing about instrumentation
  // — both sides are constants on the honest path — and it is included only so
  // the projection needs no special case. The evidence on this row is its
  // payload (`before`/`after`), which is derived from the observed events and
  // is compared in full.
  if (entry.path === "/result") return SS2_RESULT_BRIDGE_HOOK;
  const table = fixture.scenario.spellId !== undefined
    ? SS2_SPELL_HOOK_FOR_STATIC_REASON
    : SS2_HOOK_FOR_STATIC_REASON;
  if (!Object.hasOwn(table, entry.reason)) {
    throw new HookAttributionError(
      `${fixture.fixtureId} expected.mutationTrace[${index}] gives reason ${JSON.stringify(entry.reason)}, ` +
      "which no wrapper hook is mapped to, so no observation could ever be compared against it. " +
      "Add the reason to SS2_HOOK_FOR_STATIC_REASON (and, if the spell ingress owns the write, to " +
      "SS2_SPELL_HOOK_FOR_STATIC_REASON) in src/golden/observation.js, naming the AS2 ingress function " +
      "the assignment lives inside."
    );
  }
  return table[entry.reason];
}

/**
 * Match one runtime observation against a fixture's runtime-observable
 * projection: scenario, ordered samples, ordered mutations (each one's static
 * reason TRANSLATED into the hook a wrapper must attribute it to), semantic
 * events, the result event, and the final state. `expected.calculation`/
 * `expected.mutation` stay candidate-derived and are not directly observable.
 *
 * The mutation `reason` used to be stripped from BOTH sides before comparison,
 * on the grounds that the two vocabularies could not be compared. The cost of
 * that convenience was a forgery: a record attributing the hitpoint write to
 * `remove-armour`, or to `unattributed`, or to nothing the wrapper can produce,
 * matched, promoted, and yielded a golden the committed suite accepted — while
 * the hook is the record's only statement about WHERE in the game the write
 * came from, which is exactly the claim a golden rests on. Translating instead
 * of stripping costs no re-capture: all 23 promoted goldens' cited observations
 * already carry the hooks their fixtures' reasons map to.
 */
export function matchSs2ObservationToFixture(fixture, observation) {
  validateSs2OneVsOneFixture(fixture);
  validateSs2Observation(observation);
  const differences = [];

  if (
    observation.target.fixtureId !== fixture.fixtureId &&
    observation.target.fixtureId !== candidateIdFor(fixture.fixtureId)
  ) {
    pushDifference(differences, {
      path: "/target/fixtureId",
      expected: fixture.fixtureId,
      actual: observation.target.fixtureId
    });
  }
  collectDifferences(fixture.build, observation.build, "/build", differences);
  collectDifferences(fixture.scenario, observation.scenario, "/scenario", differences);

  // Cosmetic debris rolls are excluded from both sides: fixtures document
  // them, but no instrumentation can observe the opcode stream.
  const expectedSamples = fixture.samples.filter((sample) => !isCosmeticDebrisSample(sample));
  const observed = comparableSamples(observation.samples);
  if (expectedSamples.length !== observed.length) {
    pushDifference(differences, {
      path: "/samples/length",
      expected: expectedSamples.length,
      actual: observed.length
    });
  }
  const sharedSamples = Math.min(expectedSamples.length, observed.length);
  for (let index = 0; index < sharedSamples; index += 1) {
    collectDifferences(expectedSamples[index], observed[index], `/samples/${index}`, differences);
  }

  collectDifferences(
    projectTraceForMatching(
      fixture.expected.mutationTrace,
      (entry, index) => hookForFixtureMutation(fixture, entry, index)
    ),
    projectTraceForMatching(observation.mutationTrace, (entry) => entry.reason),
    "/mutationTrace",
    differences
  );
  collectDifferences(
    deriveExpectedEventsFromSs2Fixture(fixture),
    observation.events,
    "/events",
    differences
  );
  collectDifferences(fixture.expected.resultEvent, observation.resultEvent, "/resultEvent", differences);
  collectDifferences(fixture.expected.state, observation.finalState, "/finalState", differences);

  return { match: differences.length === 0, differences };
}
